# General Settings
MOCK_GPIO = False

# GPIO Pins
BUZZER_PIN = 17
VIBRATION_PINS = [27, 22]
REED_PINS = [5, 6]
ULTRASONIC_TRIGGER_PIN = 23
ULTRASONIC_ECHO_PIN = 24
ULTRASONIC_DISTANCE_CM = 30

ALERT_LED_PIN = 13
ARMED_LED_PIN = 19
ARM_DISARM_BUTTON_PIN = 26

# Notifications
EMAIL_ENABLED = False
EMAIL_SMTP_SERVER = "smtp.gmail.com"
EMAIL_SMTP_PORT = 587
EMAIL_USERNAME = "your_email@gmail.com"
EMAIL_PASSWORD = "your_password"
EMAIL_TO = "receiver@example.com"

TWILIO_ENABLED = False
TWILIO_ACCOUNT_SID = "ACxxxx"
TWILIO_AUTH_TOKEN = "your_token"
TWILIO_FROM = "+1234567890"
TWILIO_TO = "+0987654321"

# Behavior
ALARM_DURATION_SEC = 10
DEBOUNCE_SEC = 0.15
LOG_LEVEL = "INFO"
